CREATE TABLE daemon_tokens (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, name text NOT NULL DEFAULT '' CHECK (octet_length(name) <= 80), version text NOT NULL DEFAULT '' CHECK (octet_length(version) <= 40), token_hash bytea NOT NULL UNIQUE CHECK (octet_length(token_hash) = 32), created_at timestamptz NOT NULL DEFAULT now(), last_seen_at timestamptz, revoked_at timestamptz);
CREATE INDEX idx_daemon_tokens_user_live ON daemon_tokens (user_id) WHERE revoked_at IS NULL;

CREATE TABLE daemon_repos (daemon_token_id uuid NOT NULL REFERENCES daemon_tokens(id) ON DELETE CASCADE, full_name text NOT NULL CHECK (full_name ~ '^[A-Za-z0-9._-]{1,100}/[A-Za-z0-9._-]{1,100}$'), default_branch text NOT NULL CHECK (octet_length(default_branch) BETWEEN 1 AND 255), reported_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (daemon_token_id, full_name));
CREATE INDEX idx_daemon_repos_name ON daemon_repos (full_name);

CREATE TABLE automation_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, page_id text NOT NULL CHECK (octet_length(page_id) BETWEEN 1 AND 64), task_id text NOT NULL CHECK (octet_length(task_id) BETWEEN 1 AND 64), task_title text NOT NULL DEFAULT '' CHECK (octet_length(task_title) <= 500), instructions text NOT NULL DEFAULT '' CHECK (octet_length(instructions) <= 8000), repo text NOT NULL CHECK (repo ~ '^[A-Za-z0-9._-]{1,100}/[A-Za-z0-9._-]{1,100}$'), base_branch text NOT NULL CHECK (octet_length(base_branch) BETWEEN 1 AND 255), branch text NOT NULL CHECK (octet_length(branch) BETWEEN 1 AND 255), status text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','running','pr_ready','failed','canceled')), phase text NOT NULL DEFAULT 'queued' CHECK (phase IN ('queued','claimed','cloning','coding','checks','pushing','pr')), attempts int NOT NULL DEFAULT 0 CHECK (attempts >= 0), max_attempts int NOT NULL DEFAULT 3 CHECK (max_attempts >= 1), outcome text NOT NULL DEFAULT '' CHECK (outcome IN ('','ok','auth','quota','max_turns','deadline','checks','error','canceled')), pr_url text NOT NULL DEFAULT '' CHECK (octet_length(pr_url) <= 500), error_log text NOT NULL DEFAULT '' CHECK (octet_length(error_log) <= 2000), progress_log text NOT NULL DEFAULT '' CHECK (octet_length(progress_log) <= 16384), tokens_used bigint NOT NULL DEFAULT 0 CHECK (tokens_used >= 0), daemon_token_id uuid REFERENCES daemon_tokens(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now(), started_at timestamptz, finished_at timestamptz, heartbeat_at timestamptz, updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX idx_automation_runs_user_created ON automation_runs (user_id, created_at DESC, id DESC);
CREATE INDEX idx_automation_runs_user_page_created ON automation_runs (user_id, page_id, created_at DESC, id DESC);
CREATE INDEX idx_automation_runs_queued ON automation_runs (user_id, created_at ASC) WHERE status = 'queued';
CREATE INDEX idx_automation_runs_heartbeat ON automation_runs (heartbeat_at) WHERE status = 'running';
CREATE UNIQUE INDEX uq_automation_runs_active ON automation_runs (user_id, page_id, task_id) WHERE status IN ('queued','running');
