CREATE TABLE money_settings (space_id uuid PRIMARY KEY REFERENCES spaces(id) ON DELETE CASCADE, currency char(3) NOT NULL DEFAULT 'INR' CHECK (currency ~ '^[A-Z]{3}$'), locale text NOT NULL DEFAULT 'en-IN' CHECK (octet_length(locale) BETWEEN 2 AND 35), shared_by_default boolean NOT NULL DEFAULT true, approval_threshold_minor bigint NOT NULL DEFAULT 2000000 CHECK (approval_threshold_minor >= 0), monthly_close_day int NOT NULL DEFAULT 1 CHECK (monthly_close_day BETWEEN 1 AND 28), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE money_accounts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, name text NOT NULL CHECK (octet_length(name) BETWEEN 1 AND 80), kind text NOT NULL DEFAULT 'bank' CHECK (kind IN ('bank','cash','card','wallet','loan','investment')), currency char(3) NOT NULL DEFAULT 'INR' CHECK (currency ~ '^[A-Z]{3}$'), opening_balance_minor bigint NOT NULL DEFAULT 0, is_shared boolean NOT NULL DEFAULT true, owner_id uuid REFERENCES users(id) ON DELETE SET NULL, archived_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX idx_money_accounts_space ON money_accounts (space_id) WHERE archived_at IS NULL;

CREATE TABLE money_categories (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, name citext NOT NULL CHECK (octet_length(name) BETWEEN 1 AND 40), emoji text NOT NULL DEFAULT '' CHECK (octet_length(emoji) <= 16), color text NOT NULL DEFAULT '#6E7BF1' CHECK (color ~ '^#[0-9A-Fa-f]{6}$'), kind text NOT NULL DEFAULT 'expense' CHECK (kind IN ('expense','income')), sort_order int NOT NULL DEFAULT 0, archived_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX uq_money_categories_name ON money_categories (space_id, name);
CREATE INDEX idx_money_categories_space ON money_categories (space_id, sort_order) WHERE archived_at IS NULL;

CREATE TABLE money_transactions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, client_id uuid NOT NULL, account_id uuid REFERENCES money_accounts(id) ON DELETE SET NULL, category_id uuid NOT NULL REFERENCES money_categories(id) ON DELETE RESTRICT, type text NOT NULL CHECK (type IN ('expense','income')), amount_minor bigint NOT NULL CHECK (amount_minor > 0 AND amount_minor <= 100000000000), currency char(3) NOT NULL DEFAULT 'INR' CHECK (currency ~ '^[A-Z]{3}$'), occurred_on date NOT NULL, note text NOT NULL DEFAULT '' CHECK (octet_length(note) <= 280), is_shared boolean NOT NULL DEFAULT true, paid_by uuid REFERENCES users(id) ON DELETE SET NULL, created_by uuid REFERENCES users(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE UNIQUE INDEX uq_money_transactions_client ON money_transactions (space_id, client_id);
CREATE INDEX idx_money_transactions_feed ON money_transactions (space_id, occurred_on DESC, id DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_money_transactions_category ON money_transactions (space_id, category_id, occurred_on) WHERE deleted_at IS NULL;
CREATE INDEX idx_money_transactions_payer ON money_transactions (space_id, paid_by, occurred_on) WHERE deleted_at IS NULL;

CREATE TABLE money_budgets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, category_id uuid NOT NULL REFERENCES money_categories(id) ON DELETE CASCADE, period text NOT NULL DEFAULT 'monthly' CHECK (period IN ('monthly')), limit_minor bigint NOT NULL CHECK (limit_minor > 0), starts_on date NOT NULL DEFAULT date_trunc('month', now())::date, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX uq_money_budgets_category ON money_budgets (space_id, category_id, period);

CREATE TABLE money_bills (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, name text NOT NULL CHECK (octet_length(name) BETWEEN 1 AND 120), emoji text NOT NULL DEFAULT '' CHECK (octet_length(emoji) <= 16), category_id uuid REFERENCES money_categories(id) ON DELETE SET NULL, account_id uuid REFERENCES money_accounts(id) ON DELETE SET NULL, amount_minor bigint NOT NULL CHECK (amount_minor > 0), day_of_month int NOT NULL CHECK (day_of_month BETWEEN 1 AND 28), auto_log boolean NOT NULL DEFAULT false, is_shared boolean NOT NULL DEFAULT true, paid_by uuid REFERENCES users(id) ON DELETE SET NULL, last_logged_on date, archived_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX idx_money_bills_space ON money_bills (space_id, day_of_month) WHERE archived_at IS NULL;

CREATE TABLE money_holdings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, owner_id uuid REFERENCES users(id) ON DELETE SET NULL, name text NOT NULL CHECK (octet_length(name) BETWEEN 1 AND 120), badge text NOT NULL DEFAULT '' CHECK (octet_length(badge) <= 8), asset_type text NOT NULL DEFAULT 'other' CHECK (asset_type IN ('mutual_fund','stocks','gold','retirement','debt','cash','other')), units numeric(24,6) NOT NULL CHECK (units > 0), avg_cost_minor bigint NOT NULL CHECK (avg_cost_minor >= 0), last_price_minor bigint NOT NULL CHECK (last_price_minor >= 0), day_change_bps int NOT NULL DEFAULT 0, sip_minor bigint NOT NULL DEFAULT 0 CHECK (sip_minor >= 0), currency char(3) NOT NULL DEFAULT 'INR' CHECK (currency ~ '^[A-Z]{3}$'), color text NOT NULL DEFAULT '#6E7BF1' CHECK (color ~ '^#[0-9A-Fa-f]{6}$'), priced_at timestamptz, archived_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX idx_money_holdings_space ON money_holdings (space_id) WHERE archived_at IS NULL;

CREATE TABLE money_invites (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), space_id uuid NOT NULL REFERENCES spaces(id) ON DELETE CASCADE, email citext NOT NULL CHECK (octet_length(email) BETWEEN 3 AND 254), role text NOT NULL DEFAULT 'editor' CHECK (role IN ('editor','viewer')), token_hash bytea NOT NULL UNIQUE CHECK (octet_length(token_hash) = 32), invited_by uuid REFERENCES users(id) ON DELETE SET NULL, expires_at timestamptz NOT NULL, accepted_at timestamptz, accepted_by uuid REFERENCES users(id) ON DELETE SET NULL, revoked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX uq_money_invites_open ON money_invites (space_id, email) WHERE accepted_at IS NULL AND revoked_at IS NULL;
CREATE INDEX idx_money_invites_email ON money_invites (email) WHERE accepted_at IS NULL AND revoked_at IS NULL;
