package escrow

import (
	"bytes"
	"encoding/base64"
	"testing"

	"golang.org/x/crypto/nacl/box"
)

func masterKey() []byte {
	k := make([]byte, KeySize)
	for i := range k {
		k[i] = byte(i + 1)
	}
	return k
}

func decode(t *testing.T, raw string) []byte {
	t.Helper()
	b, err := base64.StdEncoding.DecodeString(raw)
	if err != nil {
		t.Fatalf("decode %q: %v", raw, err)
	}
	return b
}

// The client seals space keys with libsodium's crypto_box_seal, hand-built in
// TypeScript in packages/crypto. The server now has to open those same boxes to
// re-wrap a key for a recovered device. A byte of divergence between the two
// implementations would not throw — it would hand a device a key that decrypts
// a ledger into noise — so this vector was produced by the real TypeScript
// client and is pinned here rather than generated by this package.
const (
	clientPublicKey  = "z+eN6x/WfVAJdP1mpBTC1+CwxJk8Xtq8gSF5GN/GRxg="
	clientPrivateKey = "a3e/PXvbKvJ5fUGtWWhdjD3UEqwXqzyzQ7PgQPqpgj0="
	clientSpaceKey   = "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8="
	clientSealed     = "xaoHFxF/VXI8dn/wCQsczYJXPu3cVhtRrhbhMiluEmQoyHtyuu8AltGzUJ9Q+951q11HpM8mzYWdTORdBt7F8S8xnZ6dgFrQcDG+Te14q/8="
)

func TestOpensASealedBoxTheTypeScriptClientProduced(t *testing.T) {
	// Arrange
	var public, private [KeySize]byte
	copy(public[:], decode(t, clientPublicKey))
	copy(private[:], decode(t, clientPrivateKey))

	// Act
	opened, ok := box.OpenAnonymous(nil, decode(t, clientSealed), &public, &private)

	// Assert
	if !ok {
		t.Fatal("Go could not open a sealed box the TypeScript client produced; the two crypto implementations have diverged")
	}
	if !bytes.Equal(opened, decode(t, clientSpaceKey)) {
		t.Fatalf("opened %x, want %x", opened, decode(t, clientSpaceKey))
	}
}

func TestClientCanOpenWhatTheServerSeals(t *testing.T) {
	// Arrange — seal to the client's own public key, as a re-wrap does.
	var public, private [KeySize]byte
	copy(public[:], decode(t, clientPublicKey))
	copy(private[:], decode(t, clientPrivateKey))
	spaceKey := decode(t, clientSpaceKey)

	// Act
	sealed, err := box.SealAnonymous(nil, spaceKey, &public, nil)
	if err != nil {
		t.Fatalf("seal: %v", err)
	}

	// Assert — same construction, so the holder of the private half opens it.
	opened, ok := box.OpenAnonymous(nil, sealed, &public, &private)
	if !ok || !bytes.Equal(opened, spaceKey) {
		t.Fatal("a box sealed by the server did not open under the recipient's key")
	}
}

func TestRewrapMovesAKeyFromEscrowToADevice(t *testing.T) {
	// Arrange — an account escrow key, and a household key wrapped to it the way
	// a client wraps one at household creation.
	keeper := New(masterKey())
	escrowPublic, escrowSealed, err := keeper.NewAccountKey()
	if err != nil {
		t.Fatalf("mint escrow key: %v", err)
	}

	spaceKey := decode(t, clientSpaceKey)
	var escrowRecipient [KeySize]byte
	copy(escrowRecipient[:], escrowPublic)
	escrowWrap, err := box.SealAnonymous(nil, spaceKey, &escrowRecipient, nil)
	if err != nil {
		t.Fatalf("wrap to escrow: %v", err)
	}

	var devicePublic, devicePrivate [KeySize]byte
	copy(devicePublic[:], decode(t, clientPublicKey))
	copy(devicePrivate[:], decode(t, clientPrivateKey))

	// Act
	deviceWrap, err := keeper.RewrapTo(escrowSealed, escrowPublic, escrowWrap, devicePublic[:])
	if err != nil {
		t.Fatalf("rewrap: %v", err)
	}

	// Assert — the device opens it and gets the original household key back.
	opened, ok := box.OpenAnonymous(nil, deviceWrap, &devicePublic, &devicePrivate)
	if !ok {
		t.Fatal("the device could not open the re-wrapped key")
	}
	if !bytes.Equal(opened, spaceKey) {
		t.Fatalf("recovered %x, want %x", opened, spaceKey)
	}
}

func TestStoredEscrowKeyIsNotThePlainPrivateKey(t *testing.T) {
	// Arrange
	keeper := New(masterKey())

	// Act
	public, sealed, err := keeper.NewAccountKey()
	if err != nil {
		t.Fatalf("mint escrow key: %v", err)
	}

	// Assert — what goes in the database is sealed, longer than a raw key, and
	// carries neither half in the clear.
	if len(sealed) <= KeySize {
		t.Fatalf("stored key is %d bytes; a sealed key must be longer than the %d-byte key it hides", len(sealed), KeySize)
	}
	if bytes.Contains(sealed, public) {
		t.Fatal("the stored escrow key contains its own public half verbatim")
	}
}

func TestAWrongMasterKeyCannotOpenAnEscrowKey(t *testing.T) {
	// Arrange — a key sealed under one master, opened under another.
	original := New(masterKey())
	escrowPublic, escrowSealed, err := original.NewAccountKey()
	if err != nil {
		t.Fatalf("mint escrow key: %v", err)
	}

	other := make([]byte, KeySize)
	for i := range other {
		other[i] = byte(200 - i)
	}
	rotated := New(other)

	// Act
	_, err = rotated.RewrapTo(escrowSealed, escrowPublic, []byte("irrelevant"), make([]byte, KeySize))

	// Assert
	if err == nil {
		t.Fatal("a different master key opened the escrow key")
	}
}

func TestEscrowRefusesToWorkWithoutAMasterKey(t *testing.T) {
	// Arrange
	keeper := New(nil)

	// Act
	_, _, err := keeper.NewAccountKey()

	// Assert — a deployment with no secret must refuse escrow, not invent one.
	if err != ErrNotConfigured {
		t.Fatalf("err = %v, want ErrNotConfigured", err)
	}
	if keeper.Configured() {
		t.Fatal("a keeper with no master key reported itself configured")
	}
}
